import Head from "next/head";

function Home() {
  return (
    <div>
      <Head>
        <title>Foodieland</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="uppercase text-blue-500 text-center text-xl font-bold"></div>
    </div>
  );
}
export default Home;
